name: Build NovaFlux (cloud) — diagnose

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK (manual)
        env:
          ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
        run: |
          set -eux
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          cd "$ANDROID_SDK_ROOT/cmdline-tools"
          curl -sSL -o clt.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q clt.zip
          mv cmdline-tools latest
          SDKMAN="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          yes | "$SDKMAN" --sdk_root="$ANDROID_SDK_ROOT" --licenses || true
          "$SDKMAN" --sdk_root="$ANDROID_SDK_ROOT" --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH

      - name: Unzip project
        run: |
          set -euxo pipefail
          sudo apt-get update && sudo apt-get install -y unzip
          ZIP=$(ls -1 *.zip | head -n 1 || true)
          [ -z "$ZIP" ] && { echo "No ZIP found at repo root"; exit 1; }
          unzip -o "$ZIP" -d extracted
          ROOT=$(ls -1d extracted/NovaFlux_* extracted/NovaFlux* 2>/dev/null | head -n 1 || true)
          [ -z "$ROOT" ] && ROOT="extracted"
          shopt -s dotglob
          mv "$ROOT"/* ./

      - name: Force Gradle 8.10.2 + Kotlin 1.9.24 + Java 17
        run: |
          set -euxo pipefail
          # Gradle wrapper
          if [ -f gradle/wrapper/gradle-wrapper.properties ]; then
            sed -i 's#distributionUrl=.*#distributionUrl=https\\://services.gradle.org/distributions/gradle-8.10.2-bin.zip#' gradle/wrapper/gradle-wrapper.properties || true
          fi
          chmod +x ./gradlew || true
          # Repos + options
          echo "org.gradle.jvmargs=-Xmx3g -Dkotlin.daemon.jvm.options=-Xmx2g" >> gradle.properties || true
          echo "android.useAndroidX=true" >> gradle.properties || true
          echo "android.enableJetifier=true" >> gradle.properties || true
          # API 34 par sécurité
          sed -i 's/compileSdk *35/compileSdk 34/g' app/build.gradle || true
          sed -i 's/targetSdk *35/targetSdk 34/g' app/build.gradle || true
          # Kotlin & jvmTarget
          for f in $(git ls-files | grep -E '\.gradle(\.kts)?$' || true); do
            sed -i "s/kotlin-gradle-plugin:[0-9.]\+/kotlin-gradle-plugin:1.9.24/g" "$f" || true
            sed -i "s/id[[:space:]]*['\"]org.jetbrains.kotlin.android['\"][[:space:]]*version[[:space:]]*['\"][^'\"]*['\"]/id 'org.jetbrains.kotlin.android' version '1.9.24'/g" "$f" || true
          done
          cat >> app/build.gradle <<'EOF'

          // --- CI patch: jvmTarget 17 ---
          android {
              compileOptions {
                  sourceCompatibility JavaVersion.VERSION_17
                  targetCompatibility JavaVersion.VERSION_17
              }
              kotlinOptions {
                  jvmTarget = '17'
              }
          }
          tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
              kotlinOptions { jvmTarget = "17" }
          }
          // --- end patch ---
          EOF

      - name: Print Gradle env
        run: |
          ./gradlew -v || true
          echo "---- gradle.properties ----"
          cat gradle.properties || true
          echo "---- app/build.gradle (tail) ----"
          tail -n 80 app/build.gradle || true

      - name: Clean & build (verbose)
        run: |
          set -euxo pipefail
          ./gradlew clean :app:assembleDebug --stacktrace --info --warning-mode all --no-daemon --console=plain

      - name: Upload APK (if built)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: NovaFlux-APK
          path: app/build/outputs/apk/debug/app-debug.apk