name: Build NovaFlux (cloud)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Installation manuelle du SDK Android (fiable)
      - name: Install Android SDK (manual)
        env:
          ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
        run: |
          set -eux
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          cd "$ANDROID_SDK_ROOT/cmdline-tools"
          curl -sSL -o clt.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q clt.zip
          mv cmdline-tools latest
          SDKMAN="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"

          # Accepter les licences (ignore la fin de pipe)
          set +o pipefail || true
          yes | "$SDKMAN" --sdk_root="$ANDROID_SDK_ROOT" --licenses >/dev/null 2>&1 || true
          set -o pipefail || true

          # Installer avec retries (réseau capricieux)
          for i in 1 2 3; do
            "$SDKMAN" --sdk_root="$ANDROID_SDK_ROOT" --install \
              "platform-tools" "platforms;android-34" "build-tools;34.0.0" && break || sleep 5
          done

          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH

      # Détection automatique du ZIP et extraction
      - name: Unzip project (auto-detect)
        run: |
          set -euxo pipefail
          sudo apt-get update && sudo apt-get install -y unzip
          echo "Repo content:" ; ls -la
          ZIP=$(ls -1 *.zip | head -n 1 || true)
          echo "Using ZIP=$ZIP"
          if [ -z "$ZIP" ]; then echo "No ZIP found at repo root"; exit 1; fi
          unzip -o "$ZIP" -d extracted
          echo "Extracted content:" ; ls -la extracted
          ROOT=$(ls -1d extracted/NovaFlux_* extracted/NovaFlux* 2>/dev/null | head -n 1 || true)
          if [ -z "$ROOT" ]; then ROOT="extracted"; fi
          shopt -s dotglob
          mv "$ROOT"/* ./
          sed -i 's/compileSdk 35/compileSdk 34/g' app/build.gradle || true
          sed -i 's/targetSdk 35/targetSdk 34/g' app/build.gradle || true

      - name: Build Debug APK
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.10.2
          arguments: ":app:assembleDebug"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: NovaFlux-APK
          path: app/build/outputs/apk/debug/app-debug.apk