name: Build NovaFlux (cloud)

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'novaflux-iptv-android15.zip'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0

      - name: Unzip project
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          unzip -o "novaflux-iptv-android15.zip" -d .
          ROOT=$(ls -1d NovaFlux* Nova* | head -n1)
          echo "ROOT=$ROOT"
          shopt -s dotglob
          mv "$ROOT"/* .
          rmdir "$ROOT" || true
          # Harmoniser les SDK si besoin
          sed -i 's/compileSdk *35/compileSdk 34/g' app/build.gradle || true
          sed -i 's/targetSdk *35/targetSdk 34/g' app/build.gradle || true

      - name: Build Debug APK
        uses: gradle/gradle-build-action@v3
        with:
          arguments: ":app:assembleDebug"

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: NovaFlux-APK
          path: app/build/outputs/apk/debug/app-debug.apk
              id 'com.android.application'
              id 'org.jetbrains.kotlin.android'
          }
          android {
              namespace 'com.example.iptvreader'
              compileSdk 34
              defaultConfig {
                  applicationId "com.example.iptvreader"
                  minSdk 26
                  targetSdk 34
                  versionCode 1
                  versionName "1.0"
                  vectorDrawables { useSupportLibrary = true }
              }
              buildTypes {
                  release {
                      minifyEnabled false
                      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                  }
              }
              compileOptions {
                  sourceCompatibility JavaVersion.VERSION_17
                  targetCompatibility JavaVersion.VERSION_17
              }
              kotlinOptions {
                  jvmTarget = '17'
                  freeCompilerArgs += ['-Xjvm-default=all-compatibility']
              }
              buildFeatures { viewBinding true }
          }
          dependencies {
              implementation platform('org.jetbrains.kotlin:kotlin-bom:1.9.24')
              implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.24'
              implementation 'androidx.core:core-ktx:1.13.1'
              implementation 'androidx.appcompat:appcompat:1.7.0'
              implementation 'com.google.android.material:material:1.12.0'
              implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.8.6'
              implementation 'androidx.media3:media3-exoplayer:1.4.1'
              implementation 'androidx.media3:media3-ui:1.4.1'
              implementation 'com.squareup.okhttp3:okhttp:4.12.0'
              implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1'
          }
          EOF

      - name: Force Gradle 8.10.2
        run: |
          mkdir -p gradle/wrapper
          cat > gradle/wrapper/gradle-wrapper.properties <<'EOF'
          distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          distributionUrl=https\://services.gradle.org/distributions/gradle-8.10.2-bin.zip
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists
          EOF
          if [ ! -f gradlew ]; then
            curl -sL https://raw.githubusercontent.com/gradle/gradle/master/gradlew -o gradlew
          fi
          chmod +x gradlew

      - name: Clean & build (verbose)
        run: |
          ./gradlew clean :app:assembleDebug --stacktrace --warning-mode all --no-daemon
          echo "APK path: app/build/outputs/apk/debug/app-debug.apk"

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: NovaFlux-APK
          path: app/build/outputs/apk/debug/app-debug.apk