name: Build NovaFlux (cloud)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0

      - name: Unzip project
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          unzip -o "novaflux-iptv-android15.zip" -d .
          ROOT=$(ls -1d NovaFlux_* | head -n 1)
          shopt -s dotglob
          mv "$ROOT"/* ./
          sed -i 's/compileSdk 35/compileSdk 34/g' app/build.gradle || true
          sed -i 's/targetSdk 35/targetSdk 34/g' app/build.gradle || true

      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.4
          arguments: ":app:assembleDebug"

      - uses: actions/upload-artifact@v4
        with:
          name: NovaFlux-APK
          path: app/build/outputs/apk/debug/app-debug.apk